FROM nginx:latest

WORKDIR /usr/share/nginx/html

COPY index.html index.html


## Run the following commands to build and run the image
## docker image build -t nginx-with-html .
## docker container run -p 80:80 --rm nginx-with-html

## To push this image to dockerHub
## docker login
## docker image tag nginx-with-html:latest rafadelnero/nginx-with-html:latest
## docker push rafadelnero/nginx-with-html

## The -f flag will specify a dockerfile when building an image

